Add synchronous api
replikativ/hitchhiker-tree pull request #35
Opened 2022-05-12 16:17 UTC by kordano

based on #34

2022-09-28 08:02 UTC, whilo requested changes
Looks good except for the calva file.

2022-09-28 08:02 UTC, whilo commented on .calva/output-window/output.calva-repl
> +; This is the Calva evaluation results output window.
Can you remove the .calva output?

2022-10-04 09:54 UTC, jsmassa commented on .calva/output-window/output.calva-repl
> +; This is the Calva evaluation results output window.
It's being ignored now

2022-10-06 05:46 UTC, whilo approved these changes

2022-10-06 05:47 UTC, whilo approved these changes

2022-10-06 05:53 UTC, whilo commented
@jsmassa Sorry for rerequesting your review, it was an accident while I tried to resolve my conversation. It looks good to me now!

2022-10-18 19:34 UTC, merged